import {
  ClerkProvider
} from '@clerk/nextjs'
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '500', '700'],
  variable: '--font-poppis',
});

export const metadata: Metadata = {
  title: "EventEZ",
  description: "Generated by create next app",
  icons: {
    icon: '/assests/images/logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={poppins.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
